def substring_search(dna_str, sub_str):
    r = -1  
    while True:
        r = dna_str.find(sub_str, r + 1) 
        if r == -1:  
            break
        print(r + 1, end=" ")  

dna_str = "CAACTTAGCGCGAAGCATCAAGCATCTTAAGCATCAAGCATCAAAGCATCCAAAGCATCCCGAAGCATCCAAGCATCTTAAAGCATCAAGCATCGGCAAGCATCTCATAAAGCATCCAAGCATCAAGCATCCCAAAGCATCGGGGCGGAAAGCATCGGTAAGCATCTTAAGCATCAAGCATCAGGAAAGCATCAAGCATCCTCAAGCATCTAAGCATCAAGCATCGCAGAAGCATCTTAAGCATCACGCATAAGCATCAAGCATCAAAGCATCAAGCATCAGAAGCATCATATCAAGCATCCAAGCATCCCGGCTGCGCCGCAAGCATCTTTAAGCATCAAGCATCAAGCATCGTCTAAAGCATCTCAAAGCATCCAAAGCATCCTGTGCATCAAGCATCAAGCATCTGGCAAGCATCAAGCATCAATAAGCATCGCCCAAGCATCTAAGCATCGAAAAGCATCATTCGGTAAGCATCAAAAGCATCGAGGATGCAAAGCATCTCCACTAAGCATCAAGCATCAAAAGCATCGAGACCTGAAGCATCCGCAAAGCATCAAGCATCAAGCATCGACTGGTTCAAGATAAACTCAGTAAATGAAGCATCATATGCCTCGGACAGTCTAAGCATCTAGCAAGCATCGTGCTTAAGCATCTAAAGCATCCCCATTTGAAGCATCCAAGCATCAAGCATCAAGCATCAAGCATCATCGTAAGCATCCGATACAACAAAGCATCAGCATTCAATTGGAAGCATCCTCACAAGCATCAGTTGTTAGAAGCATCAAAGCATCAAGCATCAAGCATCAGAAGCATCTAAGCATCCAAGCATCTTTAAAGCATCAAGCATCGTAAGCATCAAGCATCGAAGCATCTACTTAAGCATCAAGCATCAAGCATC"
sub_str = "AAGCATCAA"

substring_search(dna_str, sub_str)
